[package]
edition = "2018"

authors = ["Daniel Egger <daniel@eggers-club.de>"]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
description = "Peripheral access API for STM32F4 series microcontrollers"
documentation = "https://docs.rs/stm32f4xx-hal"
keywords = [
    "arm",
    "cortex-m",
    "stm32f4xx",
    "hal",
]
license = "0BSD"
name = "stm32f4xx-hal"
readme = "README.md"
repository = "https://github.com/stm32-rs/stm32f4xx-hal"
version = "0.9.0"

[package.metadata.docs.rs]
features = ["stm32f429", "rt", "usb_fs", "can", "i2s", "fsmc_lcd"]
targets = ["thumbv7em-none-eabihf"]

[dependencies]
bxcan = { version = ">=0.4, <0.6", optional = true }
cortex-m = "0.7"
cortex-m-rt = "0.6.10"
nb = "1"
rand_core = "0.6"
rtcc = "0.2"
stm32f4 = "0.13"
synopsys-usb-otg = { version = "0.2.0", features = ["cortex-m"], optional = true }
sdio-host = { version = "0.5.0", optional = true }
embedded-dma = "0.1.2"
bare-metal = { version = "1" }
cast = { default-features = false, version = "0.2.2" }
void = { default-features = false, version = "1.0.2" }
embedded-hal = { features = ["unproven"], version = "0.2.3" }
display-interface = { version = "0.4.0", optional = true }

[dependencies.stm32_i2s_v12x]
version = "0.2.0"
optional = true

[dev-dependencies]
panic-semihosting = "0.5.3"
cortex-m-semihosting = "0.3.3"
arrayvec = { version = "0.5.1", default-features = false }
panic-halt = "0.2.0"
ssd1306 = "0.5"
embedded-graphics = "0.6.2"
usb-device = "0.2.5"
usbd-serial = "0.1.0"
micromath = "1.0.0"
cortex-m-rtic = "0.5.6"
st7789 = "0.5.0"
panic-rtt-core = "0.2.1"

[features]
device-selected = []
rt = ["stm32f4/rt"]
# Note: stm32f4 has only one feature for some very similar device families,
# so it's intended for e.g. stm32f405/415 to both enable stm32f4/stm32f405.
stm32f401 = ["stm32f4/stm32f401", "device-selected",
    "gpiod", "gpioe",
    "i2c3",
    "otg-fs",
    "sdio",
    "spi3", "spi4",
    "tim2",
]
stm32f405 = ["stm32f4/stm32f405", "device-selected",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "fsmc",
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi",
    "i2c3",
    "otg-fs",
    "otg-hs",
    "rng",
    "sdio",
    "spi3",
    "tim2", "tim8",
    "usart3", "uart4", "uart5",
]
stm32f407 = ["stm32f4/stm32f407", "device-selected",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "fsmc",
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi",
    "i2c3",
    "otg-fs",
    "otg-hs",
    "rng",
    "sdio",
    "spi3",
    "tim2", "tim8",
    "usart3", "uart4", "uart5",
]
stm32f410 = ["stm32f4/stm32f410", "device-selected",
    "dac",
    "spi5",
]
stm32f411 = ["stm32f4/stm32f411", "device-selected",
    "gpiod", "gpioe",
    "i2c3",
    "otg-fs",
    "sdio",
    "tim2",
    "spi3", "spi4", "spi5",
]
stm32f412 = ["stm32f4/stm32f412", "device-selected",
    "can1", "can2",
    "fsmc",
    "gpiod", "gpioe", "gpiof", "gpiog",
    "i2c3",
    "otg-fs",
    "rng",
    "sdio",
    "spi3", "spi4", "spi5",
    "tim2", "tim8",
    "usart3",
]
stm32f413 = ["stm32f4/stm32f413", "device-selected",
    "can1", "can2",
    "dac",
    "fsmc",
    "fmpi2c1",
    "gpiod", "gpioe", "gpiof", "gpiog",
    "i2c3",
    "otg-fs",
    "rng",
    "sdio",
    "spi3", "spi4", "spi5",
    "tim2", "tim8",
    "usart3", "uart4", "uart5", "uart7", "uart8", "uart9", "uart10",
]
stm32f415 = ["stm32f4/stm32f405", "device-selected",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "fsmc",
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi",
    "i2c3",
    "otg-fs",
    "otg-hs",
    "rng",
    "sdio",
    "spi3",
    "tim2", "tim8",
    "usart3", "uart4", "uart5",
]
stm32f417 = ["stm32f4/stm32f407", "device-selected",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "fsmc",
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi",
    "i2c3",
    "otg-fs",
    "otg-hs",
    "rng",
    "sdio",
    "spi3",
    "tim2", "tim8",
    "usart3", "uart4", "uart5",
]
stm32f423 = ["stm32f4/stm32f413", "device-selected",
    "can1", "can2",
    "dac",
    "fsmc",
    "fmpi2c1",
    "gpiod", "gpioe", "gpiof", "gpiog",
    "i2c3",
    "otg-fs",
    "rng",
    "sdio",
    "spi3", "spi4", "spi5",
    "tim2", "tim8",
    "usart3", "uart4", "uart5", "uart7", "uart8", "uart9", "uart10",
]
stm32f427 = ["stm32f4/stm32f427", "device-selected",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "fsmc",
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi", "gpioj", "gpiok",
    "i2c3",
    "otg-fs",
    "otg-hs",
    "rng",
    "sdio",
    "spi3", "spi4", "spi5", "spi6",
    "tim2", "tim8",
    "usart3", "uart4", "uart5", "uart7", "uart8",
]
stm32f429 = ["stm32f4/stm32f429", "device-selected",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "fmc",
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi", "gpioj", "gpiok",
    "i2c3",
    "otg-fs",
    "otg-hs",
    "rng",
    "sdio",
    "spi3", "spi4", "spi5", "spi6",
    "tim2", "tim8",
    "usart3", "uart4", "uart5", "uart7", "uart8",
]
stm32f437 = ["stm32f4/stm32f427", "device-selected",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "fsmc",
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi", "gpioj", "gpiok",
    "i2c3",
    "otg-fs",
    "otg-hs",
    "rng",
    "sdio",
    "spi3", "spi4", "spi5", "spi6",
    "tim2", "tim8",
    "usart3", "uart4", "uart5", "uart7", "uart8",
]
stm32f439 = ["stm32f4/stm32f429", "device-selected",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "fmc",
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi", "gpioj", "gpiok",
    "i2c3",
    "otg-fs",
    "otg-hs",
    "rng",
    "sdio",
    "spi3", "spi4", "spi5", "spi6",
    "tim2", "tim8",
    "usart3", "uart4", "uart5", "uart7", "uart8",
]
stm32f446 = ["stm32f4/stm32f446", "device-selected",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "fmc",
    "gpiod", "gpioe", "gpiof", "gpiog",
    "i2c3",
    "otg-fs",
    "otg-hs",
    "spi3", "spi4",
    "tim2", "tim8",
    "usart3", "uart4", "uart5",
]
stm32f469 = ["stm32f4/stm32f469", "device-selected",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "fmc",
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi", "gpioj", "gpiok",
    "i2c3",
    "otg-fs",
    "otg-hs",
    "rng",
    "sdio",
    "spi3", "spi4", "spi5", "spi6",
    "tim2", "tim8",
    "usart3", "uart4", "uart5", "uart7", "uart8",
]
stm32f479 = ["stm32f4/stm32f469", "device-selected",
    "adc2", "adc3",
    "can1", "can2",
    "dac",
    "fmc",
    "gpiod", "gpioe", "gpiof", "gpiog", "gpioi", "gpioj", "gpiok",
    "i2c3",
    "otg-fs",
    "otg-hs",
    "rng",
    "sdio",
    "spi3", "spi4", "spi5", "spi6",
    "tim2", "tim8",
    "usart3", "uart4", "uart5", "uart7", "uart8",
]

usb_fs = ["synopsys-usb-otg", "synopsys-usb-otg/fs"]
usb_hs = ["synopsys-usb-otg", "synopsys-usb-otg/hs"]

can = ["bxcan"]

i2s = ["stm32_i2s_v12x"]

fsmc_lcd = ["display-interface"]

adc2 = []
adc3 = []
can1 = []
can2 = []
dac = []
fmc = []
fsmc = []
fmpi2c1 = []
gpiod = []
gpioe = []
gpiof = []
gpiog = []
gpioi = []
gpioj = []
gpiok = []
i2c3 = []
otg-fs = []
otg-hs = []
rng = []
sdio = []
spi3 = []
spi4 = []
spi5 = []
spi6 = []
tim2 = []
tim8 = []
usart3 = []
uart4 = []
uart5 = []
uart7 = []
uart8 = []
uart9 = []
uart10 = []

[profile.dev]
debug = true
lto = true

[profile.release]
debug = true
lto = true
opt-level = "s"

[[example]]
name = "blinky-timer-irq"
required-features = ["rt", "tim2"] # stm32f411

[[example]]
name = "usb_serial"
required-features = ["otg-fs", "usb_fs"] # stm32f401

[[example]]
name = "sd"
required-features = ["gpiod", "sdio", "sdio-host"] # stm32f405

[[example]]
name = "delay-syst-blinky"
required-features = ["device-selected"] # stm32f411

[[example]]
name = "delay-timer-blinky"
required-features = ["device-selected"] # stm32f411

[[example]]
name = "dwt-blinky"
required-features = ["gpiog"] # "stm32f429"

[[example]]
name = "ssd1306-image"
required-features = ["device-selected"] # stm32f411

[[example]]
name = "stopwatch-with-ssd1306-and-interrupts"
required-features = ["rt", "tim2"] # stm32f411

[[example]]
name = "analog-stopwatch-with-spi-ssd1306"
required-features = ["rt", "spi4", "tim2", "gpioe", "gpiog"] # stm32f429

[[example]]
name = "rng-display"
required-features = ["rng"] # stm32f407

[[example]]
name = "qei"
required-features = ["tim2"] # stm32f411

[[example]]
name = "can-send"
required-features = ["can", "can1", "can2"] # stm32f405

[[example]]
name = "i2s-audio-out"
required-features = ["stm32f411", "i2s"]

[[example]]
name = "i2s-audio-out-dma"
required-features = ["stm32f411", "rt", "i2s"]

[[example]]
name = "rtic"
required-features = ["gpiod"] # stm32f407

[[example]]
name = "adc_dma_rtic"
required-features = ["device-selected"] # stm32f401

[[example]]
name = "serial-9bit"
required-features = ["gpiod"] # stm32f411

[[example]]
name = "st7789-lcd"
required-features = ["fsmc", "fsmc_lcd"] # stm32f412

[[example]]
name = "f413disco_lcd_ferris"
required-features = ["gpiod", "gpioe", "gpiof", "gpiog", "fsmc", "fsmc_lcd"] # stm32f413

[[example]]
name= "pwm-input"
required-features = ["tim8"] # stm32f446
